### ISSUE TITLE
Agrovoc URI does not 4xt

### ISSUE THREAD

**Issue by siemvaessen** [IATI/IATI-Codelists-NonEmbedded#279] opened 2018-12-10 13:02 UTC
At http://reference.iatistandard.org/203/codelists/TagVocabulary/

code 1 Agrovoc has a broken URI in it:

http://artemide.art.uniroma2.it:8081/agrovoc/agrovoc/en/

Could this be fixed?

**Comment by andylolz** [comment] 2018-12-10 14:03
I guess the problem is the weird port. This appears to work:
http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/

However, I don’t know what the actual URL should be.

**Comment by PetyaKangalova** [comment] 2019-01-09 15:33
Thanks for responding @andylolz  

I got in touch with the AGROVOC team to check which is the most stable and relevant link to add and received the below response: 
> We moved some of the infrastructure last year, so to search and browse AGROVOC this would indeed be the best link:  http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/
> 
> If there is a need to download data or use web services, the general page may also be useful  http://aims.fao.org/vest-registry/vocabularies/agrovoc  (but the download information is accessible from the browseable site too). 

I will go ahead and update the link to : http://agrovoc.uniroma2.it/agrovoc/agrovoc/en/

**Comment by amy-silcock** [comment] 2019-01-15 12:42
Closing the issue as the change has been implemented

**Closed by amy-silcock** 2019-01-15 12:42 UTC
